version: '3.7'
services:
  redis:
    image: redis:alpine
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --port $REDISPORT --save 20 1 --loglevel warning --requirepass $REDISPASSWORD
    volumes:
      - cache:/data
  bot:
    image: "bot"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
      - ./app
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    depends_on:
      - redis